name: Jest

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  general:
    if: ${{ github.repository_owner == 'amattu2' }}
    runs-on: ubuntu-latest
    steps:
      # Clone repository
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      # Install dependencies
      - name: "Install Dependencies"
        run: npm ci

      # Run Jest tests
      - name: "Run Jest"
        run: npm run test:ci

      # Run ESLint
      - name: "Run ESLint"
        run: npm run lint . --quiet # Ignore warnings
